# Generated by Django 2.1.3 on 2018-12-26 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photourl',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
